### ISSUE TITLE
Calling the deliver_set method on sale.order triggers TypeError: cannot marshal None unless allow_none is enabled

### ISSUE THREAD

**Issue by esciara** [tinyerp/erppeek#87]
Hi there,

I am trying to add a delivery carrier to a sale order. 

When I call `sale_order_record.delivery_set()`, which seems to be the method to call for that purpose, I get a `TypeError: cannot marshal None unless allow_none is enabled`. 

Probably a newby problem, but I could not get around understanding how to make it work/workaround it/how to enable `allow_none`... 

Any help/pointers?

Stack trace below:
```
      Traceback (most recent call last):
        File "/Users/emmanuelsciara/Documents/Development/git-repos/odoo/odoo/openerp/service/wsgi_server.py", line 57, in xmlrpc_return
          response = xmlrpclib.dumps((result,), methodresponse=1, allow_none=False, encoding=None)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1091, in dumps
          data = m.dumps(params)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 638, in dumps
          dump(v, write)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 660, in __dump
          f(self, value, write)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 664, in dump_nil
          raise TypeError, "cannot marshal None unless allow_none is enabled"
      TypeError: cannot marshal None unless allow_none is enabled

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/Users/emmanuelsciara/virtual_envs/odoo_pilote/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/Users/emmanuelsciara/virtual_envs/odoo_pilote/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/Users/emmanuelsciara/Documents/Development/git-repos/odoo/odoo-pilote/oerpscenario_functional_labo.features/steps/pricelist_with_5_percent_discount.py", line 81, in i_add_to_the_sale_order_the_delivery_carrier
          context.last_sale_order.delivery_set()
        File "/Users/emmanuelsciara/virtual_envs/odoo_pilote/lib/python2.7/site-packages/erppeek.py", line 1524, in wrapper
          res = self._execute(attr, [self.id], *params, **kwargs)
        File "/Users/emmanuelsciara/virtual_envs/odoo_pilote/lib/python2.7/site-packages/erppeek.py", line 712, in execute
          res = self._execute(obj, method, *params)
        File "/Users/emmanuelsciara/virtual_envs/odoo_pilote/lib/python2.7/site-packages/erppeek.py", line 402, in <lambda>
          wrapper = lambda s, *args: s._dispatch(name, args)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
          verbose=self.__verbose
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1280, in request
          return self.single_request(host, handler, request_body, verbose)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1313, in single_request
          return self.parse_response(response)
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1490, in parse_response
          return u.close()
        File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 799, in close
          raise Fault(**self._stack[0])
      Fault: cannot marshal None unless allow_none is enabled
```

**Comment by esciara** [comment]
OK, I am a bit puzzled here.

I am using the latest version (1.6.3) .

Looking at the code, `allow_none` seems to be set to `True` according to [these two lines of code](https://github.com/tinyerp/erppeek/blob/884b02a5c666e73bb65e707843a062a2b8e2e48b/erppeek.py#L355-L356) in the `Service` class, which is used by the `Client` class to set up its proxies:
```python
            proxy = ServerProxy(rpcpath + endpoint,
                                transport=transport, allow_none=True)
```

It does not seem to take this into account...

Also tried to look for a workaround and to replicate the call that is made on the UI when clicking on "Set price"
![image](https://cloud.githubusercontent.com/assets/1336689/15806716/613bd2a6-2b4a-11e6-86d0-f7b1b987b22e.png)

The call appears on the logs as:
```
2016-06-05 16:22:36,847 30074 INFO labo_erppeek_test openerp.models.unlink: User #1 deleted sale.order.line records with IDs: [33]
2016-06-05 16:22:36,971 30074 DEBUG labo_erppeek_test openerp.http.rpc.request: call_button: sale.order delivery_set: time:0.553s mem: 2636428k -> 2636428k (diff: 0k)
2016-06-05 16:22:36,978 30074 INFO labo_erppeek_test werkzeug: 127.0.0.1 - - [05/Jun/2016 16:22:36] "POST /web/dataset/call_button HTTP/1.1" 200 -
```
Not sure how to replicate this `openerp.http.rpc.request: call_button: sale.order delivery_set` call...

**Comment by esciara** [comment]
As for an update, I reproduced the issue with the `xmlrpclib` library. Same problem appears. So it probably not an erppeek problem. 

Here is the code I used on a locally installed and running Odoo 9:
```python
server = 'http://localhost:8069'
username = 'admin'  # The Odoo user
pwd = 'admin'  # The password of the Odoo user
dbname = 'ErpPeekDemoDatabase'  # The Odoo database

#
# Use erppeek to create the database, install the modules (it is easier :) )
#
import erppeek

client = erppeek.Client(server)
try:
    client.login(user=username, password=pwd, database=dbname)
except erppeek.Error as erppeek_err:
    # Database probably does not exist. Create it
    client.create_database(passwd=pwd, database=dbname)

client.install('sale')
client.install('website_sale_delivery')

#
# Use xmlrpclib to create records
#
import xmlrpclib

# OpenERP Common login Service proxy object
rpcpath = server + '/xmlrpc/'
sock_common = xmlrpclib.ServerProxy(rpcpath + 'common', allow_none=True)
uid = sock_common.login(dbname, username, pwd)

sock = xmlrpclib.ServerProxy(rpcpath + 'object', allow_none=True)

# Calling the remote ORM create method to create the records
delivery_carrier_id = sock.execute(dbname, uid, pwd, 'delivery.carrier', 'create',
                                   {'name': 'Test delivery carrier',
                                    'delivery_type': 'fixed',
                                    'fixed_price': 10,
                                    'product_type': 'service',
                                    'partner_id': 1})
sale_order_id = sock.execute(dbname, uid, pwd, 'sale.order', 'create', {'carrier_id': delivery_carrier_id,
                                                                        'partner_id': 1})

# Calling the delivery_set method, which returns nothing and 
# makes xmlrpc throw a `TypeError: cannot marshal None unless allow_none is enabled` error
result = sock.execute(dbname, uid, pwd, 'sale.order', 'delivery_set', sale_order_id)
```

**Comment by esciara** [comment]
Well... That helped me find a workaround. I realised that the `delivery_set` method is still run despite the marshalling error. So workaround is to catch the `xmlrpclib.Fault` thrown for this. and move on.

This is *really* ugly... but should do the trick until we get to the bottom of this problem.

**Comment by esciara** [comment]
This is a known limitation of XMLRPC. Odoo code needs to be changed. See https://github.com/odoo/odoo/issues/12289#issuecomment-223842864 for details.
